---
- name: Load variables based on the OS distribution and release name
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

- name: Combine sets of dependencies to install
  include_vars: combine-dependencies.yml
